services:
  dev:
    image: dev_ronin
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/src/
      - ~/.gitconfig:/.gitconfig
      - ~/.ssh/:/home/user/.ssh/
      - /var/run/docker.sock:/var/run/docker-host.sock
    tty: true
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
    extra_hosts:
      - host.docker.internal:host-gateway
